language: python
python:
  - "2.7"
  - "pypy"
install:
- make build
script: make test
sudo: false
before_deploy:
  - make kingpin.zip
deploy:
  provider: releases
  api_key:
    secure: TMRRd3PeZIRf4wvD2Bh+ykvvBVIztE6M6JE89WBb/CbaIbdUqoDoldYjybYbbXDPPPs+ybVOYZTwMylx6TDy40WsYlzlaabnbTZedvUWDC3GcqD3E4I5XMBVBColP1cKZqHYaa/p23V9QfJFoXCJzGJ5VWOXclj0A0NEvb+oUpU=
  file: kingpin.zip
  on:
    tags: true
    python: "2.7"
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+[a-z]?$"
    repo: Nextdoor/kingpin
