# https://github.com/marketplace/actions/stale-branches
name: Stale Branches

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 6 * * 1-5'

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Stale Branches
        uses: crs-k/stale-branches@v8.2.2
        with:
          days-before-stale: 21
          days-before-delete: 28
          tag-committer: true
          branches-filter-regex: '^((?!dependabot|production))'
